/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mafaussu <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/02/16 14:38:33 by mafaussu          #+#    #+#             */
/*   Updated: 2022/02/16 17:15:32 by mafaussu         ###   ########lyon.fr   */
/*                                                                            */
/* ************************************************************************** */

#include "ft_printf.h"
#include "limits.h"
#include "stdlib.h"
#include "stdio.h"
#include "string.h"

typedef struct s_text
{
	va_list	ap;
	int		r;
	char	*s;
}	t_test;

static int	test(int line, const char *fmt, ...)
{
	static int	r;
	static int	t;
	int			success;
	t_test		std;
	t_test		ft;

	if (!line)
		return (!printf("%i errors / %i tests\n", r, t));
	t += 1;
	va_start(std.ap, fmt);
	va_copy(ft.ap, std.ap);
	std.r = vasprintf(&std.s, fmt, std.ap);
	va_end(std.ap);
	ft.r = ft_vasprintf(&ft.s, fmt, ft.ap);
	va_end(ft.ap);
	success = !((!ft.s &&  std.s) || (ft.s && !std.s)) 
		&& (ft.r == std.r) 
		&& ((!ft.s && !std.s) || !strcmp(ft.s, std.s));
	if (!success)
	{	
		r += 1;
		printf("[%s:%i] ", __FILE__, line);
		printf("FAILURE [expected=%i got=%i '%s' '%s']\n", std.r, ft.r, std.s, ft.s);
	}
//	else
//		printf("SUCCESS [expected=%i got=%i '%s' '%s']\n", std.r, ft.r, std.s, ft.s);
	free(std.s);
	free(ft.s);
	return (!!success);
}

int	main(void)
{
	int		t2;
	int		t4;
	int		t2bis;
	char	*s;
	char	*t;

	s = "yay";
	t = s;
	test(__LINE__, "%c", 42);
	test(__LINE__, "%+0.54c", 42);
	test(__LINE__, "%+0 .5c", 42);
	test(__LINE__, "%5.4c", 42);
	test(__LINE__, "%4.5c", 42);
	test(__LINE__, "st17 %0.*x\n", 0, 0);	//
	test(__LINE__, "st17 %0.*c\n", 0, 0);	//
	test(__LINE__, "st17 %0.*d\n", 0, 0);	
	test(__LINE__, "st17 %0.*d\n", 0, 10);	
	test(__LINE__, "st17 %0.0d\n", 0, 0);	//
	test(__LINE__, "st17 %0.0d\n", 0, 10);	//
	test(__LINE__, "st17 %0.*d\n", 10, 10);
	test(__LINE__, "st17 %0.*d\n", 10, 0);	
	test(__LINE__, "st17 %0.0d\n", 10, 10);	
	test(__LINE__, "st17 %0.0d\n", 10, 0);

	return (test(0,0));

	test(__LINE__, "st17 %.*x\n", 0, 0);	//
	test(__LINE__, "st17 %.*c\n", 0, 0);	
	test(__LINE__, "st17 %.*d\n", 0, 0);	//
	test(__LINE__, "st17 %.*d\n", 0, 10);	
	test(__LINE__, "st17 %.0d\n", 0, 0);	//
	test(__LINE__, "st17 %.0d\n", 0, 10);	
	test(__LINE__, "st17 %.*d\n", 10, 10);	
	test(__LINE__, "st17 %.*d\n", 10, 0);	
	test(__LINE__, "st17 %.0d\n", 10, 10);	
	test(__LINE__, "st17 %.0d\n", 10, 0);	

	test(__LINE__, "st17 %.*x\n", 0, 0);	
	test(__LINE__, "st17 %.*c\n", 0, 0);	
	test(__LINE__, "st17 %.*d\n", 0, 0);	
	test(__LINE__, "st17 %.*d\n", 0, 10);	
	test(__LINE__, "st17 %.0d\n", 0, 0);	
	test(__LINE__, "st17 %.0d\n", 0, 10);	
	test(__LINE__, "st17 %.*d\n", 10, 10);	
	test(__LINE__, "st17 %.*d\n", 10, 0);	
	test(__LINE__, "st17 %.0d\n", 10, 10);	
	test(__LINE__, "st17 %.0d\n", 10, 0);		

	test(__LINE__, "%---7.1 .8c", 42);
	test(__LINE__, "%80+80+80c", 42);
	test(__LINE__, "% 8 .5c", 42);
	test(__LINE__, "%-0 +72.15c", 42);
	test(__LINE__, "%669c", 42);
	test(__LINE__, "%0.0c", 42);
	test(__LINE__, "%s", "42");
	test(__LINE__, "%+0.54s", "42");
	test(__LINE__, "%+0 .5s", "42");
	test(__LINE__, "%045.58s", "42");
	test(__LINE__, "%---7.1 .8s", "42");
	test(__LINE__, "%80+80+80s", "42");
	test(__LINE__, "% 8 .5s", "42");
	test(__LINE__, "%-0 +72.15s", "42");
	test(__LINE__, "%669s", "42");
	test(__LINE__, "%0.0s", "42");
	test(__LINE__, "%s", "42");
	test(__LINE__, "neg7 %*.*s\n", -1586, 15, "coucou");
	test(__LINE__, "neg7 %*.*s\n", 1586, -15, "coucou");
	test(__LINE__, "neg7 %*.*s\n", -1586, -15, "coucou");
	test(__LINE__, "%p", 42);
	test(__LINE__, "%+0.54p", 42);
	test(__LINE__, "%+0 .5p", 42);
	test(__LINE__, "%045.5p", 42);
	test(__LINE__, "%---7.1 .8p", 42);
	test(__LINE__, "%80+80+80p", 42);
	test(__LINE__, "% 8 .5p", 42);
	test(__LINE__, "%-0 +72.15p", 42);
	test(__LINE__, "%669p", 42);
	test(__LINE__, "%0.0p", 42);
	test(__LINE__, "%669d", 42);
	test(__LINE__, "%0.0d", 42);
	test(__LINE__, "%i", 42);
	test(__LINE__, "%+0.54i", 42);
	test(__LINE__, "%+0 .5i", 42);
	test(__LINE__, "%045.58i", 42);
	test(__LINE__, "%---7.1 .8i", 42);
	test(__LINE__, "%80+80+80i", 42);
	test(__LINE__, "% 8 .5i", 42);
	test(__LINE__, "%-0 +72.15i", 42);
	test(__LINE__, "%u", 42);
	test(__LINE__, "%+0.54u", 42);
	test(__LINE__, "%+0 .5u", 42);
	test(__LINE__, "%045.58u", 42);
	test(__LINE__, "%---7.1 .8u", 42);
	test(__LINE__, "%80+80+80u", 42);
	test(__LINE__, "% 8 .5u", 42);
	test(__LINE__, "%-0 +72.15u", 42);
	test(__LINE__, "%669u", 42);
	test(__LINE__, "%0.0u", 42);
	test(__LINE__, "%o", 42);
	test(__LINE__, "%+0.54o", 42);
	test(__LINE__, "%+0 .5o", 42);
	test(__LINE__, "%045.58o", 42);
	test(__LINE__, "%---7.1 .8o", 42);
	test(__LINE__, "%80+80+80o", 42);
	test(__LINE__, "% 8 .5o", 42);
	test(__LINE__, "%-0 +72.15o", 42);
	test(__LINE__, "%669o", 42);
	test(__LINE__, "%0.0o", 42);
	test(__LINE__, "%%", 42);
	test(__LINE__, "%+0.54%", 42);
	test(__LINE__, "%+0 .5%", 42);
	test(__LINE__, "%045.58%", 42);
	test(__LINE__, "%---7.1 .8%", 42);
	test(__LINE__, "%80+80+80%", 42);
	test(__LINE__, "% 8 .5%", 42);
	test(__LINE__, "%-0 +72.15%", 42);
	test(__LINE__, "%669%", 42);
	test(__LINE__, "%0.0%", 42);
	test(__LINE__, "");
	test(__LINE__, "1");
	test(__LINE__, "%.s", "hello");
	test(__LINE__, "%s", "hello");
	test(__LINE__, "%s", (char[3]) {'\0', 'a', '\0'});
	test(__LINE__, "%10c lol %c 1", 0, 0);
	test(__LINE__, "%*c", -1000, 'a');
	test(__LINE__, "%-*s", -1000, "a");
	test(__LINE__, "%-*s", -1000, "");
	test(__LINE__, "%1%");
	test(__LINE__, "%2%");
	test(__LINE__, "%10%");
	test(__LINE__, "%1c", '1');
	test(__LINE__, "%2c", '1');
	test(__LINE__, "%10c", '1');
	test(__LINE__, "%--1s", "");
	test(__LINE__, "%5s", "Hello");
	test(__LINE__, "%6s", "Hello");
	test(__LINE__, "%1i", -101);
	test(__LINE__, "%1i", 0);
	test(__LINE__, "%2i", 0);
	test(__LINE__, "%10i", 0);
	test(__LINE__, "%1i", -1);
	test(__LINE__, "%2i", -1);
	test(__LINE__, "%3i", -1);
	test(__LINE__, "%9i", INT_MAX);
	test(__LINE__, "%10i", INT_MAX);
	test(__LINE__, "%11i", INT_MAX);
	test(__LINE__, "%1d", 0);
	test(__LINE__, "%2d", 0);
	test(__LINE__, "%10d", 0);
	test(__LINE__, "%1d", -1);
	test(__LINE__, "%2d", -1);
	test(__LINE__, "%3d", -1);
	test(__LINE__, "%9d", INT_MAX);
	test(__LINE__, "%10d", INT_MAX);
	test(__LINE__, "%11d", INT_MAX);
	test(__LINE__, "%1u", 0);
	test(__LINE__, "%2u", 0);
	test(__LINE__, "%10u", 0);
	test(__LINE__, "%1u", -1);
	test(__LINE__, "%2u", -1);
	test(__LINE__, "%3u", -1);
	test(__LINE__, "%9u", UINT_MAX);
	test(__LINE__, "%10u", UINT_MAX);
	test(__LINE__, "%11u", UINT_MAX);
	test(__LINE__, "%1x", 0);
	test(__LINE__, "%2x", 0);
	test(__LINE__, "%10x", 0);
	test(__LINE__, "%1x", -1);
	test(__LINE__, "%2x", -1);
	test(__LINE__, "%3x", -1);
	test(__LINE__, "%9x", UINT_MAX);
	test(__LINE__, "%10x", UINT_MAX);
	test(__LINE__, "%11x", UINT_MAX);
	test(__LINE__, "%1X", 0);
	test(__LINE__, "%2X", 0);
	test(__LINE__, "%10X", 0);
	test(__LINE__, "%1X", -1);
	test(__LINE__, "%2X", -1);
	test(__LINE__, "%3X", -1);
	test(__LINE__, "%9X", UINT_MAX);
	test(__LINE__, "%10X", UINT_MAX);
	test(__LINE__, "%11X", UINT_MAX);
	test(__LINE__, "%1p", (void*)42);
	test(__LINE__, "%4p", (void*)1);
	test(__LINE__, "%5p", (void*)42);
	test(__LINE__, "%12.2slol\n", NULL);
	test(__LINE__, "%--8.10slol\n", NULL);
	test(__LINE__, "%8.10s\n", NULL);
	test(__LINE__, "%.*slol\n",  3, NULL);
	test(__LINE__, "%*.*hilol\n", -16, 2, 4242);
	test(__LINE__, "%*.*hhulol\n", -16, 2, INT_MAX);
	test(__LINE__, "%0-*.*c		lol\n", -10, -5, 'q', &t4);
	test(__LINE__, "%0-16p %x %X %#x %#X\n", ULONG_LONG_MAX, INT_MAX, INT_MAX, INT_MAX, INT_MAX);
	test(__LINE__, "%0-16p %x %X %#x %#X\n", ULONG_LONG_MAX, INT_MAX, INT_MAX, INT_MAX, INT_MAX);
	test(__LINE__, "1");
	test(__LINE__, "%lclol%lc", 0, 0);
	test(__LINE__, "%lc", '\\');
	test(__LINE__, "%lc", 0x0376);
	test(__LINE__, "%lc", 0x0376);
	test(__LINE__, "%lc", WCHAR_MAX);
	test(__LINE__, "%ls", (wchar_t[2]){'/', 0});
	test(__LINE__, "%lc", INT_MAX / 2);
	test(__LINE__, "%lc", INT_MAX - 2);
	test(__LINE__, "%lc", WCHAR_MAX);
	test(__LINE__, "%lc", 316);
	test(__LINE__, "%llllllllllllllli", LLONG_MAX);
	test(__LINE__, "%hhhhhhhhi", LLONG_MAX);
	test(__LINE__, "%zzwwwi", LLONG_MAX);
	test(__LINE__, "%zzwwwi", LLONG_MAX);
	test(__LINE__, "%hhh100#zo", "hello world");
	test(__LINE__, "%lhhlllllls", (void*)"hello world");
	test(__LINE__, "%hhhhll#s", "hello");
	test(__LINE__, "%hhhh#s", "hello");
	test(__LINE__, "%hhhhlll %llllllllllllllhhhhhu %lllhhhhhl %hhhhhhhhlllllhhhl  %hhhhhhhhhl %lllllhhhhh ", LLONG_MAX, LLONG_MAX, LLONG_MAX, LLONG_MAX, LLONG_MAX, LLONG_MAX);
	test(__LINE__, "%0.0hhh#x     ", LLONG_MAX);
	test(__LINE__, "%zzzzzu", ULONG_LONG_MAX);
	test(__LINE__, "%lllllllllllllllx", LLONG_MAX);
	test(__LINE__, "%hhhhhhhhi", LLONG_MAX);
	test(__LINE__, "%zzwwwx", LLONG_MAX);
	test(__LINE__, "");
	test(__LINE__, "1");
	test(__LINE__, "%%");
	test(__LINE__, "%%%%");
	test(__LINE__, "%%%%%%");
	test(__LINE__, "%c", '1');
	test(__LINE__, "%c", -207);
	test(__LINE__, "%c", 256 + 48);
	test(__LINE__, "%c", INT32_MAX);
	test(__LINE__, "%c%%", '3');
	test(__LINE__, "0%c", 0);
	test(__LINE__, "%c", -129);
	test(__LINE__, "%c", 128);
	test(__LINE__, "%c", 0);
	test(__LINE__, "%s", "Hello");
	test(__LINE__, "%s%%", "Hello3");
	test(__LINE__, "%s", "");
	test(__LINE__, "%s", "1");
	test(__LINE__, "%i", 0);
	test(__LINE__, "%i", -1);
	test(__LINE__, "%i", -42);
	test(__LINE__, "%i", 1);
	test(__LINE__, "%i", 42);
	test(__LINE__, "%i", INT_MAX);
	test(__LINE__, "%i", INT_MAX + 1);
	test(__LINE__, "%i", INT_MIN);
	test(__LINE__, "%i", 1000);
	test(__LINE__, "%i", -1000);
	test(__LINE__, "%d", 0);
	test(__LINE__, "%d", -1);
	test(__LINE__, "%d", -42);
	test(__LINE__, "%d", 1);
	test(__LINE__, "%d", 42);
	test(__LINE__, "%d", INT_MAX);
	test(__LINE__, "%d", INT_MAX + 1);
	test(__LINE__, "%d", INT_MIN);
	test(__LINE__, "%d", 1000);
	test(__LINE__, "%d", -1000);
	test(__LINE__, "%u", 0);
	test(__LINE__, "%u", -1);
	test(__LINE__, "%u", 1);
	test(__LINE__, "%u", 42);
	test(__LINE__, "%u", UINT_MAX);
	test(__LINE__, "%u", UINT_MAX + 1);
	test(__LINE__, "%u", 1000);
	test(__LINE__, "%x", 0);
	test(__LINE__, "%x", -1);
	test(__LINE__, "%x", -42);
	test(__LINE__, "%x", 1);
	test(__LINE__, "%x", 42);
	test(__LINE__, "%x", INT_MAX);
	test(__LINE__, "%x", INT_MAX + 1);
	test(__LINE__, "%x", INT_MIN);
	test(__LINE__, "%x", 1000);
	test(__LINE__, "%x", -1000);
	test(__LINE__, "%X", 0);
	test(__LINE__, "%X", -1);
	test(__LINE__, "%X", -42);
	test(__LINE__, "%X", 1);
	test(__LINE__, "%X", 42);
	test(__LINE__, "%X", INT_MAX);
	test(__LINE__, "%X", INT_MAX + 1);
	test(__LINE__, "%X", INT_MIN);
	test(__LINE__, "%X", 1000);
	test(__LINE__, "%X", -1000);
	test(__LINE__, "%p", (void*)1);
	test(__LINE__, "%p", (void*)-1);
	test(__LINE__, "%p", (void*)42);
	test(__LINE__, "%p", (void*)1000);
	test(__LINE__, "%p", (void*)ULONG_MAX);
	test(__LINE__, "%p", (void*)ULONG_MAX + 1);
	test(__LINE__, "%*c", -1000, 'a');
	test(__LINE__, "%*s", -1000, "");
	test(__LINE__, "%1%");
	test(__LINE__, "%2%");
	test(__LINE__, "%10%");
	test(__LINE__, "%1c", '1');
	test(__LINE__, "%2c", '1');
	test(__LINE__, "%10c", '1');
	test(__LINE__, "%1s", "");
	test(__LINE__, "%5s", "Hello");
	test(__LINE__, "%6s", "Hello");
	test(__LINE__, "%1i", 0);
	test(__LINE__, "%2i", 0);
	test(__LINE__, "%10i", 0);
	test(__LINE__, "%1i", -1);
	test(__LINE__, "%2i", -1);
	test(__LINE__, "%3i", -1);
	test(__LINE__, "%9i", INT_MAX);
	test(__LINE__, "%10i", INT_MAX);
	test(__LINE__, "%11i", INT_MAX);
	test(__LINE__, "%1d", 0);
	test(__LINE__, "%2d", 0);
	test(__LINE__, "%10d", 0);
	test(__LINE__, "%1d", -1);
	test(__LINE__, "%2d", -1);
	test(__LINE__, "%3d", -1);
	test(__LINE__, "%9d", INT_MAX);
	test(__LINE__, "%10d", INT_MAX);
	test(__LINE__, "%11d", INT_MAX);
	test(__LINE__, "%1u", 0);
	test(__LINE__, "%2u", 0);
	test(__LINE__, "%10u", 0);
	test(__LINE__, "%1u", -1);
	test(__LINE__, "%2u", -1);
	test(__LINE__, "%3u", -1);
	test(__LINE__, "%9u", UINT_MAX);
	test(__LINE__, "%10u", UINT_MAX);
	test(__LINE__, "%11u", UINT_MAX);
	test(__LINE__, "%1x", 0);
	test(__LINE__, "%2x", 0);
	test(__LINE__, "%10x", 0);
	test(__LINE__, "%1x", -1);
	test(__LINE__, "%2x", -1);
	test(__LINE__, "%3x", -1);
	test(__LINE__, "%9x", UINT_MAX);
	test(__LINE__, "%10x", UINT_MAX);
	test(__LINE__, "%11x", UINT_MAX);
	test(__LINE__, "%1X", 0);
	test(__LINE__, "%2X", 0);
	test(__LINE__, "%10X", 0);
	test(__LINE__, "%1X", -1);
	test(__LINE__, "%2X", -1);
	test(__LINE__, "%3X", -1);
	test(__LINE__, "%9X", UINT_MAX);
	test(__LINE__, "%10X", UINT_MAX);
	test(__LINE__, "%11X", UINT_MAX);
	test(__LINE__, "%1p", (void*)42);
	test(__LINE__, "%5p", (void*)42);
	test(__LINE__, "%-1%");
	test(__LINE__, "%-2%");
	test(__LINE__, "%-10%");
	test(__LINE__, "%-1c", '1');
	test(__LINE__, "%-2c", '1');
	test(__LINE__, "%-10c", '1');
	test(__LINE__, "%-1s", "");
	test(__LINE__, "%-5s", "Hello");
	test(__LINE__, "%-6s", "Hello");
	test(__LINE__, "%-1i", 0);
	test(__LINE__, "%-2i", 0);
	test(__LINE__, "%-10i", 0);
	test(__LINE__, "%-1i", -1);
	test(__LINE__, "%-2i", -1);
	test(__LINE__, "%-3i", -1);
	test(__LINE__, "%-9i", INT_MAX);
	test(__LINE__, "%-10i", INT_MAX);
	test(__LINE__, "%-11i", INT_MAX);
	test(__LINE__, "%-1d", 0);
	test(__LINE__, "%-2d", 0);
	test(__LINE__, "%-10d", 0);
	test(__LINE__, "%-1d", -1);
	test(__LINE__, "%-2d", -1);
	test(__LINE__, "%-3d", -1);
	test(__LINE__, "%-9d", INT_MAX);
	test(__LINE__, "%-10d", INT_MAX);
	test(__LINE__, "%-11d", INT_MAX);
	test(__LINE__, "%-1u", 0);
	test(__LINE__, "%-2u", 0);
	test(__LINE__, "%-10u", 0);
	test(__LINE__, "%-1u", -1);
	test(__LINE__, "%-2u", -1);
	test(__LINE__, "%-3u", -1);
	test(__LINE__, "%-9u", UINT_MAX);
	test(__LINE__, "%-10u", UINT_MAX);
	test(__LINE__, "%-11u", UINT_MAX);
	test(__LINE__, "%-1x", 0);
	test(__LINE__, "%-2x", 0);
	test(__LINE__, "%-10x", 0);
	test(__LINE__, "%-1x", -1);
	test(__LINE__, "%-2x", -1);
	test(__LINE__, "%-3x", -1);
	test(__LINE__, "%-9x", UINT_MAX);
	test(__LINE__, "%-10x", UINT_MAX);
	test(__LINE__, "%-11x", UINT_MAX);
	test(__LINE__, "%-1X", 0);
	test(__LINE__, "%-2X", 0);
	test(__LINE__, "%-10X", 0);
	test(__LINE__, "%-1X", -1);
	test(__LINE__, "%-2X", -1);
	test(__LINE__, "%-3X", -1);
	test(__LINE__, "%-9X", UINT_MAX);
	test(__LINE__, "%-10X", UINT_MAX);
	test(__LINE__, "%-11X", UINT_MAX);
	test(__LINE__, "%-1p", (void*)42);
	test(__LINE__, "%-5p", (void*)42);
	test(__LINE__, "%01i", 0);
	test(__LINE__, "%02i", 0);
	test(__LINE__, "%020.10s", "hello");
	test(__LINE__, "%010.10s", "hello");
	test(__LINE__, "%010i", 0);
	test(__LINE__, "%01i", -1);
	test(__LINE__, "%02i", -1);
	test(__LINE__, "%03i", -1);
	test(__LINE__, "%09i", INT_MAX);
	test(__LINE__, "%010i", INT_MAX);
	test(__LINE__, "%011i", INT_MAX);
	test(__LINE__, "%01d", 0);
	test(__LINE__, "%02d", 0);
	test(__LINE__, "%010d", 0);
	test(__LINE__, "%01d", -1);
	test(__LINE__, "%02d", -1);
	test(__LINE__, "%03d", -1);
	test(__LINE__, "%09d", INT_MAX);
	test(__LINE__, "%010d", INT_MAX);
	test(__LINE__, "%011d", INT_MAX);
	test(__LINE__, "%01u", 0);
	test(__LINE__, "%02u", 0);
	test(__LINE__, "%010u", 0);
	test(__LINE__, "%01u", -1);
	test(__LINE__, "%02u", -1);
	test(__LINE__, "%03u", -1);
	test(__LINE__, "%09u", UINT_MAX);
	test(__LINE__, "%010u", UINT_MAX);
	test(__LINE__, "%011u", UINT_MAX);
	test(__LINE__, "%01x", 0);
	test(__LINE__, "%02x", 0);
	test(__LINE__, "%010x", 0);
	test(__LINE__, "%01x", -1);
	test(__LINE__, "%02x", -1);
	test(__LINE__, "%03x", -1);
	test(__LINE__, "%09x", UINT_MAX);
	test(__LINE__, "%010x", UINT_MAX);
	test(__LINE__, "%011x", UINT_MAX);
	test(__LINE__, "%01X", 0);
	test(__LINE__, "%02X", 0);
	test(__LINE__, "%010X", 0);
	test(__LINE__, "%01X", -1);
	test(__LINE__, "%02X", -1);
	test(__LINE__, "%03X", -1);
	test(__LINE__, "%09X", UINT_MAX);
	test(__LINE__, "%010X", UINT_MAX);
	test(__LINE__, "%011X", UINT_MAX);
	test(__LINE__, "%0-10d", 42);
	test(__LINE__, "%-010d", 42);
	test(__LINE__, "%.0%");
	test(__LINE__, "%.%");
	test(__LINE__, "%0.%");
	test(__LINE__, "%0.0%");
	test(__LINE__, "%.1%");
	test(__LINE__, "%.%");
	test(__LINE__, "%1.%");
	test(__LINE__, "%.%");
	test(__LINE__, "%0.1%");
	test(__LINE__, "%1.1%");
	test(__LINE__, "%1.0%");
	test(__LINE__, "%1.0%");
	test(__LINE__, "%1.1%");
	test(__LINE__, "%0.1%");
	test(__LINE__, "%.1%");
	test(__LINE__, "%.2%");
	test(__LINE__, "%.10%");
	test(__LINE__, "%.0c", 'a');
	test(__LINE__, "%.c", 'a');
	test(__LINE__, "%0.c", 'a');
	test(__LINE__, "%0.0c", 'a');
	test(__LINE__, "%.1c", 'a');
	test(__LINE__, "%.c", 'a');
	test(__LINE__, "%1.c", 'a');
	test(__LINE__, "%.c", 'a');
	test(__LINE__, "%0.1c", 'a');
	test(__LINE__, "%1.1c", 'a');
	test(__LINE__, "%1.0c", 'a');
	test(__LINE__, "%1.0c", 'a');
	test(__LINE__, "%1.1c", 'a');
	test(__LINE__, "%0.1c", 'a');
	test(__LINE__, "%.1c", 'a');
	test(__LINE__, "%.2c", 'a');
	test(__LINE__, "%.10c", 'a');
	test(__LINE__, "%.s", "hello world");
	test(__LINE__, "%.0s", "hello world");
	test(__LINE__, "%.s", "hello world");
	test(__LINE__, "%0.s", "hello world");
	test(__LINE__, "%0.0s", "hello world");
	test(__LINE__, "%.1s", "hello world");
	test(__LINE__, "%.s", "hello world");
	test(__LINE__, "%1.s", "hello world");
	test(__LINE__, "%.s", "hello world");
	test(__LINE__, "%0.1s", "hello world");
	test(__LINE__, "%1.1s", "hello world");
	test(__LINE__, "%1.0s", "hello world");
	test(__LINE__, "%1.0s", "hello world");
	test(__LINE__, "%1.1s", "hello world");
	test(__LINE__, "%0.1s", "hello world");
	test(__LINE__, "%.1s", "hello world");
	test(__LINE__, "%.2s", "hello world");
	test(__LINE__, "%.10s", "hello world");
	test(__LINE__, "%.0s", "");
	test(__LINE__, "%.1s", "");
	test(__LINE__, "%.3s", "");
	test(__LINE__, "%.0s", "Hello");
	test(__LINE__, "%.1s", "Hello");
	test(__LINE__, "%.2s", "Hello");
	test(__LINE__, "%.5s", "Hello");
	test(__LINE__, "%.6s", "Hello");
	test(__LINE__, "%.7s", "Hello");
	test(__LINE__, "%.0d", 'a');
	test(__LINE__, "%.d", 'a');
	test(__LINE__, "%0.d", 'a');
	test(__LINE__, "%0.0d", 'a');
	test(__LINE__, "%.1d", 'a');
	test(__LINE__, "%.d", 'a');
	test(__LINE__, "%1.d", 'a');
	test(__LINE__, "%.d", 'a');
	test(__LINE__, "%0.1d", 'a');
	test(__LINE__, "%1.1d", 'a');
	test(__LINE__, "%1.0d", 'a');
	test(__LINE__, "%1.0d", 'a');
	test(__LINE__, "%1.1d", 'a');
	test(__LINE__, "%0.1d", 'a');
	test(__LINE__, "%.1d", 'a');
	test(__LINE__, "%.2d", 'a');
	test(__LINE__, "%0.10s", "s");
	test(__LINE__, "%.10s", "s");
	test(__LINE__, "%0.10d", 'a');
	test(__LINE__, "%.10d", 'a');
	test(__LINE__, "%10.d", 'a');
	test(__LINE__, "%10.6d", 'a');
	test(__LINE__, "% 10.6d", 'a');
	test(__LINE__, "% +10.6d", 'a');
	test(__LINE__, "% +-10.6d", 'a');
	test(__LINE__, "% +-010.6d", 'a');
	test(__LINE__, "%+ -010.6d", 'a');
	test(__LINE__, "%.0d", 'a');
	test(__LINE__, "%.01d", 'a');
	test(__LINE__, "%.0+1d", 'a');
	test(__LINE__, "%.1d", 'a');
	test(__LINE__, "%.01s", "ddd");
	test(__LINE__, "%.010d", 9);
	test(__LINE__, "%10.2s", "hello world");
	test(__LINE__, "%10.2lhhh#s", "hello world");
	test(__LINE__, "%llu == %llu ?", ULONG_MAX, ULLONG_MAX);
	test(__LINE__, "%hhhhhhhhu == %llu ?", ULONG_MAX, ULLONG_MAX);
	test(__LINE__, "%10.2lhhhzzs", "hello world");
	test(__LINE__, "%10.2s", "hello world");
	test(__LINE__, "%-10.0#+-0s", "hello");
	test(__LINE__, "%.-#101.101s", "ddd");
	test(__LINE__, "%.0#s", "ddd");
	test(__LINE__, "%.#1s", "ddd");
	test(__LINE__, "%.s", "ddd");
	test(__LINE__, "%.0s", "ddd");
	test(__LINE__, "%.1s", "ddd");
	test(__LINE__, "%.+1d", 'a');
	test(__LINE__, "%10.2d", 'a');
	test(__LINE__, "%-010.+6d", 'a');
	test(__LINE__, "%-010.+-6d", 'a');
	test(__LINE__, "%- 0+10.6d", 'a');
	test(__LINE__, "%++0---10.6d", 'a');
	test(__LINE__, "%010.6d", 'a');
	test(__LINE__, "%0#10.6x", 'a');
	test(__LINE__, "%010.5s", "97");
	test(__LINE__, "%10.5d", 'a');
	test(__LINE__, "%010.-5d", 'a');
	test(__LINE__, "%010. 5d", 'a');
	test(__LINE__, "%010.+5d", 'a');
	test(__LINE__, "%+10.05d", 'a');
	test(__LINE__, "%010.+- 5d", 'a');
	test(__LINE__, "%010. + - + - 5d", 'a');
	test(__LINE__, "%010.6s", "97");
	test(__LINE__, "%.100d", 0);
	test(__LINE__, "%0.0s", NULL);
	test(__LINE__, "%0.0i", 1);
	test(__LINE__, "%3.0d", 10);
	test(__LINE__, "%0.10d", 0);
	test(__LINE__, "%1.0d", 0);
	test(__LINE__, "%-1.d", 0);
	test(__LINE__, "%.1d", 0);
	test(__LINE__, "%.0s", "hello");
	test(__LINE__, "%0.s", "hello");
	test(__LINE__, "%0.0s", "hello");
	test(__LINE__, "%0.1s", "hello");
	test(__LINE__, "%1.0s", "hello");
	test(__LINE__, "%1.s", "hello");
	test(__LINE__, "%.1s", "hello");
	test(__LINE__, "%.1d", 0);
	test(__LINE__, "%.2d", 0);
	test(__LINE__, "%.0d", 5);
	test(__LINE__, "%.1d", 5);
	test(__LINE__, "%.2d", 5);
	test(__LINE__, "%.0d", 42);
	test(__LINE__, "%.1d", 42);
	test(__LINE__, "%.2d", 42);
	test(__LINE__, "%.3d", 42);
	test(__LINE__, "%.10d", 42);
	test(__LINE__, "%.6d", 100);
	test(__LINE__, "%.0d", -1);
	test(__LINE__, "%.1d", -1);
	test(__LINE__, "%.2d", -1);
	test(__LINE__, "%.3d", -1);
	test(__LINE__, "%.0d", -42);
	test(__LINE__, "%.1d", -42);
	test(__LINE__, "%.3d", -42);
	test(__LINE__, "%.4d", -42);
	test(__LINE__, "%.20d", INT_MAX);
	test(__LINE__, "%.20d", INT_MAX + 1);
	test(__LINE__, "%.20d", INT_MIN);
	test(__LINE__, "%.20d", INT_MIN - 1);
	test(__LINE__, "%.0i", 0);
	test(__LINE__, "%.1i", 0);
	test(__LINE__, "%.2i", 0);
	test(__LINE__, "%.0i", 5);
	test(__LINE__, "%.1i", 5);
	test(__LINE__, "%.2i", 5);
	test(__LINE__, "%.0i", 42);
	test(__LINE__, "%.1i", 42);
	test(__LINE__, "%.2i", 42);
	test(__LINE__, "%.3i", 42);
	test(__LINE__, "%.10i", 42);
	test(__LINE__, "%.6i", 100);
	test(__LINE__, "%.0i", -1);
	test(__LINE__, "%.1i", -1);
	test(__LINE__, "%.2i", -1);
	test(__LINE__, "%.3i", -1);
	test(__LINE__, "%.0i", -42);
	test(__LINE__, "%.1i", -42);
	test(__LINE__, "%.3i", -42);
	test(__LINE__, "%.4i", -42);
	test(__LINE__, "%.20i", INT_MAX);
	test(__LINE__, "%.20i", INT_MAX + 1);
	test(__LINE__, "%.20i", INT_MIN);
	test(__LINE__, "%.20i", INT_MIN - 1);
	test(__LINE__, "%.0u", 0);
	test(__LINE__, "%.1u", 0);
	test(__LINE__, "%.2u", 0);
	test(__LINE__, "%.0u", 5);
	test(__LINE__, "%.1u", 5);
	test(__LINE__, "%.2u", 5);
	test(__LINE__, "%.0u", 42);
	test(__LINE__, "%.1u", 42);
	test(__LINE__, "%.2u", 42);
	test(__LINE__, "%.3u", 42);
	test(__LINE__, "%.10u", 42);
	test(__LINE__, "%.6u", 100);
	test(__LINE__, "%.0u", -1);
	test(__LINE__, "%.1u", -1);
	test(__LINE__, "%.2u", -1);
	test(__LINE__, "%.3u", -1);
	test(__LINE__, "%.0u", -42);
	test(__LINE__, "%.1u", -42);
	test(__LINE__, "%.3u", -42);
	test(__LINE__, "%.4u", -42);
	test(__LINE__, "%.20u", UINT_MAX);
	test(__LINE__, "%.20u", UINT_MAX + 1);
	test(__LINE__, "%.0x", 0);
	test(__LINE__, "%.1x", 0);
	test(__LINE__, "%.2x", 0);
	test(__LINE__, "%.0x", 5);
	test(__LINE__, "%.1x", 5);
	test(__LINE__, "%.2x", 5);
	test(__LINE__, "%.0x", 42);
	test(__LINE__, "%.1x", 42);
	test(__LINE__, "%.2x", 42);
	test(__LINE__, "%.3x", 42);
	test(__LINE__, "%.10x", 42);
	test(__LINE__, "%.6x", 100);
	test(__LINE__, "%.0x", -1);
	test(__LINE__, "%.1x", -1);
	test(__LINE__, "%.2x", -1);
	test(__LINE__, "%.3x", -1);
	test(__LINE__, "%.0x", -42);
	test(__LINE__, "%.1x", -42);
	test(__LINE__, "%.3x", -42);
	test(__LINE__, "%.4x", -42);
	test(__LINE__, "%.20x", UINT_MAX);
	test(__LINE__, "%.20x", UINT_MAX + 1);
	test(__LINE__, "%.0X", 0);
	test(__LINE__, "%.1X", 0);
	test(__LINE__, "%.2X", 0);
	test(__LINE__, "%.0X", 5);
	test(__LINE__, "%.1X", 5);
	test(__LINE__, "%.2X", 5);
	test(__LINE__, "%.0X", 42);
	test(__LINE__, "%.1X", 42);
	test(__LINE__, "%.2X", 42);
	test(__LINE__, "%.3X", 42);
	test(__LINE__, "%.10X", 42);
	test(__LINE__, "%.6X", 100);
	test(__LINE__, "%.0X", -1);
	test(__LINE__, "%.1X", -1);
	test(__LINE__, "%.2X", -1);
	test(__LINE__, "%.3X", -1);
	test(__LINE__, "%.0X", -42);
	test(__LINE__, "%.1X", -42);
	test(__LINE__, "%.3X", -42);
	test(__LINE__, "%.4X", -42);
	test(__LINE__, "%.20X", UINT_MAX);
	test(__LINE__, "%.20X", UINT_MAX + 1);
	test(__LINE__, "%1.0%");
	test(__LINE__, "%1.1%");
	test(__LINE__, "%1.2%");
	test(__LINE__, "%1.10%");
	test(__LINE__, "%2.0%");
	test(__LINE__, "%2.1%");
	test(__LINE__, "%2.2%");
	test(__LINE__, "%2.10%");
	test(__LINE__, "%10.0%");
	test(__LINE__, "%10.1%");
	test(__LINE__, "%10.2%");
	test(__LINE__, "%10.10%");
	test(__LINE__, "%1.0s", "");
	test(__LINE__, "%1.1s", "");
	test(__LINE__, "%1.2s", "");
	test(__LINE__, "%1.10s", "");
	test(__LINE__, "%5.0s", "Hello");
	test(__LINE__, "%5.1s", "Hello");
	test(__LINE__, "%5.2s", "Hello");
	test(__LINE__, "%5.10s", "Hello");
	test(__LINE__, "%6.0s", "Hello");
	test(__LINE__, "%6.1s", "Hello");
	test(__LINE__, "%6.2s", "Hello");
	test(__LINE__, "%6.10s", "Hello");
	test(__LINE__, "%1.0i", 0);
	test(__LINE__, "%1.1i", 0);
	test(__LINE__, "%1.2i", 0);
	test(__LINE__, "%1.10i", 0);
	test(__LINE__, "%2.0i", 0);
	test(__LINE__, "%2.1i", 0);
	test(__LINE__, "%2.2i", 0);
	test(__LINE__, "%2.10i", 0);
	test(__LINE__, "%10.0i", 0);
	test(__LINE__, "%10.1i", 0);
	test(__LINE__, "%10.2i", 0);
	test(__LINE__, "%10.10i", 0);
	test(__LINE__, "%1.0i", -1);
	test(__LINE__, "%1.1i", -1);
	test(__LINE__, "%1.2i", -1);
	test(__LINE__, "%1.10i", -1);
	test(__LINE__, "%2.0i", -1);
	test(__LINE__, "%2.1i", -1);
	test(__LINE__, "%2.2i", -1);
	test(__LINE__, "%2.10i", -1);
	test(__LINE__, "%3.0i", -1);
	test(__LINE__, "%3.1i", -1);
	test(__LINE__, "%3.2i", -1);
	test(__LINE__, "%3.10i", -1);
	test(__LINE__, "%9.0i", INT_MAX);
	test(__LINE__, "%9.1i", INT_MAX);
	test(__LINE__, "%9.2i", INT_MAX);
	test(__LINE__, "%9.10i", INT_MAX);
	test(__LINE__, "%10.0i", INT_MAX);
	test(__LINE__, "%10.1i", INT_MAX);
	test(__LINE__, "%10.2i", INT_MAX);
	test(__LINE__, "%10.10i", INT_MAX);
	test(__LINE__, "%11.0i", INT_MAX);
	test(__LINE__, "%11.1i", INT_MAX);
	test(__LINE__, "%11.2i", INT_MAX);
	test(__LINE__, "%11.10i", INT_MAX);
	test(__LINE__, "%1.0d", 0);
	test(__LINE__, "%1.1d", 0);
	test(__LINE__, "%1.2d", 0);
	test(__LINE__, "%1.10d", 0);
	test(__LINE__, "%2.0d", 0);
	test(__LINE__, "%2.1d", 0);
	test(__LINE__, "%2.2d", 0);
	test(__LINE__, "%2.10d", 0);
	test(__LINE__, "%10.0d", 0);
	test(__LINE__, "%10.1d", 0);
	test(__LINE__, "%10.2d", 0);
	test(__LINE__, "%10.10d", 0);
	test(__LINE__, "%1.0d", -1);
	test(__LINE__, "%1.1d", -1);
	test(__LINE__, "%1.2d", -1);
	test(__LINE__, "%1.10d", -1);
	test(__LINE__, "%2.0d", -1);
	test(__LINE__, "%2.1d", -1);
	test(__LINE__, "%2.2d", -1);
	test(__LINE__, "%2.10d", -1);
	test(__LINE__, "%3.0d", -1);
	test(__LINE__, "%3.1d", -1);
	test(__LINE__, "%3.2d", -1);
	test(__LINE__, "%3.10d", -1);
	test(__LINE__, "%9.0d", INT_MAX);
	test(__LINE__, "%9.1d", INT_MAX);
	test(__LINE__, "%9.2d", INT_MAX);
	test(__LINE__, "%9.10d", INT_MAX);
	test(__LINE__, "%10.0d", INT_MAX);
	test(__LINE__, "%10.1d", INT_MAX);
	test(__LINE__, "%10.2d", INT_MAX);
	test(__LINE__, "%10.10d", INT_MAX);
	test(__LINE__, "%11.0d", INT_MAX);
	test(__LINE__, "%11.1d", INT_MAX);
	test(__LINE__, "%11.2d", INT_MAX);
	test(__LINE__, "%11.10d", INT_MAX);
	test(__LINE__, "%1.0u", 0);
	test(__LINE__, "%1.1u", 0);
	test(__LINE__, "%1.2u", 0);
	test(__LINE__, "%1.10u", 0);
	test(__LINE__, "%2.0u", 0);
	test(__LINE__, "%2.1u", 0);
	test(__LINE__, "%2.2u", 0);
	test(__LINE__, "%2.10u", 0);
	test(__LINE__, "%10.0u", 0);
	test(__LINE__, "%10.1u", 0);
	test(__LINE__, "%10.2u", 0);
	test(__LINE__, "%10.10u", 0);
	test(__LINE__, "%1.0u", -1);
	test(__LINE__, "%1.1u", -1);
	test(__LINE__, "%1.2u", -1);
	test(__LINE__, "%1.10u", -1);
	test(__LINE__, "%2.0u", -1);
	test(__LINE__, "%2.1u", -1);
	test(__LINE__, "%2.2u", -1);
	test(__LINE__, "%2.10u", -1);
	test(__LINE__, "%3.0u", -1);
	test(__LINE__, "%3.1u", -1);
	test(__LINE__, "%3.2u", -1);
	test(__LINE__, "%3.10u", -1);
	test(__LINE__, "%9.0u", UINT_MAX);
	test(__LINE__, "%9.1u", UINT_MAX);
	test(__LINE__, "%9.2u", UINT_MAX);
	test(__LINE__, "%9.10u", UINT_MAX);
	test(__LINE__, "%10.0u", UINT_MAX);
	test(__LINE__, "%10.1u", UINT_MAX);
	test(__LINE__, "%10.2u", UINT_MAX);
	test(__LINE__, "%10.10u", UINT_MAX);
	test(__LINE__, "%11.0u", UINT_MAX);
	test(__LINE__, "%11.1u", UINT_MAX);
	test(__LINE__, "%11.2u", UINT_MAX);
	test(__LINE__, "%11.10u", UINT_MAX);
	test(__LINE__, "%1.0x", 0);
	test(__LINE__, "%1.1x", 0);
	test(__LINE__, "%1.2x", 0);
	test(__LINE__, "%1.10x", 0);
	test(__LINE__, "%2.0x", 0);
	test(__LINE__, "%2.1x", 0);
	test(__LINE__, "%2.2x", 0);
	test(__LINE__, "%2.10x", 0);
	test(__LINE__, "%10.0x", 0);
	test(__LINE__, "%10.1x", 0);
	test(__LINE__, "%10.2x", 0);
	test(__LINE__, "%10.10x", 0);
	test(__LINE__, "%1.0x", -1);
	test(__LINE__, "%1.1x", -1);
	test(__LINE__, "%1.2x", -1);
	test(__LINE__, "%1.10x", -1);
	test(__LINE__, "%2.0x", -1);
	test(__LINE__, "%2.1x", -1);
	test(__LINE__, "%2.2x", -1);
	test(__LINE__, "%2.10x", -1);
	test(__LINE__, "%3.0x", -1);
	test(__LINE__, "%3.1x", -1);
	test(__LINE__, "%3.2x", -1);
	test(__LINE__, "%3.10x", -1);
	test(__LINE__, "%9.0x", UINT_MAX);
	test(__LINE__, "%9.1x", UINT_MAX);
	test(__LINE__, "%9.2x", UINT_MAX);
	test(__LINE__, "%9.10x", UINT_MAX);
	test(__LINE__, "%10.0x", UINT_MAX);
	test(__LINE__, "%10.1x", UINT_MAX);
	test(__LINE__, "%10.2x", UINT_MAX);
	test(__LINE__, "%10.10x", UINT_MAX);
	test(__LINE__, "%11.0x", UINT_MAX);
	test(__LINE__, "%11.1x", UINT_MAX);
	test(__LINE__, "%11.2x", UINT_MAX);
	test(__LINE__, "%11.10x", UINT_MAX);
	test(__LINE__, "%1.0X", 0);
	test(__LINE__, "%1.1X", 0);
	test(__LINE__, "%1.2X", 0);
	test(__LINE__, "%1.10X", 0);
	test(__LINE__, "%2.0X", 0);
	test(__LINE__, "%2.1X", 0);
	test(__LINE__, "%2.2X", 0);
	test(__LINE__, "%2.10X", 0);
	test(__LINE__, "%10.0X", 0);
	test(__LINE__, "%10.1X", 0);
	test(__LINE__, "%10.2X", 0);
	test(__LINE__, "%10.10X", 0);
	test(__LINE__, "%1.0X", -1);
	test(__LINE__, "%1.1X", -1);
	test(__LINE__, "%1.2X", -1);
	test(__LINE__, "%1.10X", -1);
	test(__LINE__, "%2.0X", -1);
	test(__LINE__, "%2.1X", -1);
	test(__LINE__, "%2.2X", -1);
	test(__LINE__, "%2.10X", -1);
	test(__LINE__, "%3.0X", -1);
	test(__LINE__, "%3.1X", -1);
	test(__LINE__, "%3.2X", -1);
	test(__LINE__, "%3.10X", -1);
	test(__LINE__, "%9.0X", UINT_MAX);
	test(__LINE__, "%9.1X", UINT_MAX);
	test(__LINE__, "%9.2X", UINT_MAX);
	test(__LINE__, "%9.10X", UINT_MAX);
	test(__LINE__, "%10.0X", UINT_MAX);
	test(__LINE__, "%10.1X", UINT_MAX);
	test(__LINE__, "%10.2X", UINT_MAX);
	test(__LINE__, "%10.10X", UINT_MAX);
	test(__LINE__, "%11.0X", UINT_MAX);
	test(__LINE__, "%11.1X", UINT_MAX);
	test(__LINE__, "%11.2X", UINT_MAX);
	test(__LINE__, "%11.10X", UINT_MAX);
	test(__LINE__, "%-1.0%");
	test(__LINE__, "%-1.1%");
	test(__LINE__, "%-1.2%");
	test(__LINE__, "%-1.10%");
	test(__LINE__, "%-2.0%");
	test(__LINE__, "%-2.1%");
	test(__LINE__, "%-2.2%");
	test(__LINE__, "%-2.10%");
	test(__LINE__, "%-10.0%");
	test(__LINE__, "%-10.1%");
	test(__LINE__, "%-10.2%");
	test(__LINE__, "%-10.10%");
	test(__LINE__, "%-1.0s", "");
	test(__LINE__, "%-1.1s", "");
	test(__LINE__, "%-1.2s", "");
	test(__LINE__, "%-1.10s", "");
	test(__LINE__, "%-5.0s", "Hello");
	test(__LINE__, "%-5.1s", "Hello");
	test(__LINE__, "%-5.2s", "Hello");
	test(__LINE__, "%-5.10s", "Hello");
	test(__LINE__, "%-6.0s", "Hello");
	test(__LINE__, "%-6.1s", "Hello");
	test(__LINE__, "%-6.2s", "Hello");
	test(__LINE__, "%-6.10s", "Hello");
	test(__LINE__, "%-1.0i", 0);
	test(__LINE__, "%-1.1i", 0);
	test(__LINE__, "%-1.2i", 0);
	test(__LINE__, "%-1.10i", 0);
	test(__LINE__, "%-2.0i", 0);
	test(__LINE__, "%-2.1i", 0);
	test(__LINE__, "%-2.2i", 0);
	test(__LINE__, "%-2.10i", 0);
	test(__LINE__, "%-10.0i", 0);
	test(__LINE__, "%-10.1i", 0);
	test(__LINE__, "%-10.2i", 0);
	test(__LINE__, "%-10.10i", 0);
	test(__LINE__, "%-1.0i", -1);
	test(__LINE__, "%-1.1i", -1);
	test(__LINE__, "%-1.2i", -1);
	test(__LINE__, "%-1.10i", -1);
	test(__LINE__, "%-2.0i", -1);
	test(__LINE__, "%-2.1i", -1);
	test(__LINE__, "%-2.2i", -1);
	test(__LINE__, "%-2.10i", -1);
	test(__LINE__, "%-3.0i", -1);
	test(__LINE__, "%-3.1i", -1);
	test(__LINE__, "%-3.2i", -1);
	test(__LINE__, "%-3.10i", -1);
	test(__LINE__, "%-9.0i", INT_MAX);
	test(__LINE__, "%-9.1i", INT_MAX);
	test(__LINE__, "%-9.2i", INT_MAX);
	test(__LINE__, "%-9.10i", INT_MAX);
	test(__LINE__, "%-10.0i", INT_MAX);
	test(__LINE__, "%-10.1i", INT_MAX);
	test(__LINE__, "%-10.2i", INT_MAX);
	test(__LINE__, "%-10.10i", INT_MAX);
	test(__LINE__, "%-11.0i", INT_MAX);
	test(__LINE__, "%-11.1i", INT_MAX);
	test(__LINE__, "%-11.2i", INT_MAX);
	test(__LINE__, "%-11.10i", INT_MAX);
	test(__LINE__, "%-1.0d", 0);
	test(__LINE__, "%-1.1d", 0);
	test(__LINE__, "%-1.2d", 0);
	test(__LINE__, "%-1.10d", 0);
	test(__LINE__, "%-2.0d", 0);
	test(__LINE__, "%-2.1d", 0);
	test(__LINE__, "%-2.2d", 0);
	test(__LINE__, "%-2.10d", 0);
	test(__LINE__, "%-10.0d", 0);
	test(__LINE__, "%-10.1d", 0);
	test(__LINE__, "%-10.2d", 0);
	test(__LINE__, "%-10.10d", 0);
	test(__LINE__, "%-1.0d", -1);
	test(__LINE__, "%-1.1d", -1);
	test(__LINE__, "%-1.2d", -1);
	test(__LINE__, "%-1.10d", -1);
	test(__LINE__, "%-2.0d", -1);
	test(__LINE__, "%-2.1d", -1);
	test(__LINE__, "%-2.2d", -1);
	test(__LINE__, "%-2.10d", -1);
	test(__LINE__, "%-3.0d", -1);
	test(__LINE__, "%-3.1d", -1);
	test(__LINE__, "%-3.2d", -1);
	test(__LINE__, "%-3.10d", -1);
	test(__LINE__, "%-9.0d", INT_MAX);
	test(__LINE__, "%-9.1d", INT_MAX);
	test(__LINE__, "%-9.2d", INT_MAX);
	test(__LINE__, "%-9.10d", INT_MAX);
	test(__LINE__, "%-10.0d", INT_MAX);
	test(__LINE__, "%-10.1d", INT_MAX);
	test(__LINE__, "%-10.2d", INT_MAX);
	test(__LINE__, "%-10.10d", INT_MAX);
	test(__LINE__, "%-11.0d", INT_MAX);
	test(__LINE__, "%-11.1d", INT_MAX);
	test(__LINE__, "%-11.2d", INT_MAX);
	test(__LINE__, "%-11.10d", INT_MAX);
	test(__LINE__, "%-1.0u", 0);
	test(__LINE__, "%-1.1u", 0);
	test(__LINE__, "%-1.2u", 0);
	test(__LINE__, "%-1.10u", 0);
	test(__LINE__, "%-2.0u", 0);
	test(__LINE__, "%-2.1u", 0);
	test(__LINE__, "%-2.2u", 0);
	test(__LINE__, "%-2.10u", 0);
	test(__LINE__, "%-10.0u", 0);
	test(__LINE__, "%-10.1u", 0);
	test(__LINE__, "%-10.2u", 0);
	test(__LINE__, "%-10.10u", 0);
	test(__LINE__, "%-1.0u", -1);
	test(__LINE__, "%-1.1u", -1);
	test(__LINE__, "%-1.2u", -1);
	test(__LINE__, "%-1.10u", -1);
	test(__LINE__, "%-2.0u", -1);
	test(__LINE__, "%-2.1u", -1);
	test(__LINE__, "%-2.2u", -1);
	test(__LINE__, "%-2.10u", -1);
	test(__LINE__, "%-3.0u", -1);
	test(__LINE__, "%-3.1u", -1);
	test(__LINE__, "%-3.2u", -1);
	test(__LINE__, "%-3.10u", -1);
	test(__LINE__, "%-9.0u", UINT_MAX);
	test(__LINE__, "%-9.1u", UINT_MAX);
	test(__LINE__, "%-9.2u", UINT_MAX);
	test(__LINE__, "%-9.10u", UINT_MAX);
	test(__LINE__, "%-10.0u", UINT_MAX);
	test(__LINE__, "%-10.1u", UINT_MAX);
	test(__LINE__, "%-10.2u", UINT_MAX);
	test(__LINE__, "%-10.10u", UINT_MAX);
	test(__LINE__, "%-11.0u", UINT_MAX);
	test(__LINE__, "%-11.1u", UINT_MAX);
	test(__LINE__, "%-11.2u", UINT_MAX);
	test(__LINE__, "%-11.10u", UINT_MAX);
	test(__LINE__, "%-1.0x", 0);
	test(__LINE__, "%-1.1x", 0);
	test(__LINE__, "%-1.2x", 0);
	test(__LINE__, "%-1.10x", 0);
	test(__LINE__, "%-2.0x", 0);
	test(__LINE__, "%-2.1x", 0);
	test(__LINE__, "%-2.2x", 0);
	test(__LINE__, "%-2.10x", 0);
	test(__LINE__, "%-10.0x", 0);
	test(__LINE__, "%-10.1x", 0);
	test(__LINE__, "%-10.2x", 0);
	test(__LINE__, "%-10.10x", 0);
	test(__LINE__, "%-1.0x", -1);
	test(__LINE__, "%-1.1x", -1);
	test(__LINE__, "%-1.2x", -1);
	test(__LINE__, "%-1.10x", -1);
	test(__LINE__, "%-2.0x", -1);
	test(__LINE__, "%-2.1x", -1);
	test(__LINE__, "%-2.2x", -1);
	test(__LINE__, "%-2.10x", -1);
	test(__LINE__, "%-3.0x", -1);
	test(__LINE__, "%-3.1x", -1);
	test(__LINE__, "%-3.2x", -1);
	test(__LINE__, "%-3.10x", -1);
	test(__LINE__, "%-9.0x", UINT_MAX);
	test(__LINE__, "%-9.1x", UINT_MAX);
	test(__LINE__, "%-9.2x", UINT_MAX);
	test(__LINE__, "%-9.10x", UINT_MAX);
	test(__LINE__, "%-10.0x", UINT_MAX);
	test(__LINE__, "%-10.1x", UINT_MAX);
	test(__LINE__, "%-10.2x", UINT_MAX);
	test(__LINE__, "%-10.10x", UINT_MAX);
	test(__LINE__, "%-11.0x", UINT_MAX);
	test(__LINE__, "%-11.1x", UINT_MAX);
	test(__LINE__, "%-11.2x", UINT_MAX);
	test(__LINE__, "%-11.10x", UINT_MAX);
	test(__LINE__, "%-1.0X", 0);
	test(__LINE__, "%-1.1X", 0);
	test(__LINE__, "%-1.2X", 0);
	test(__LINE__, "%-1.10X", 0);
	test(__LINE__, "%-2.0X", 0);
	test(__LINE__, "%-2.1X", 0);
	test(__LINE__, "%-2.2X", 0);
	test(__LINE__, "%-2.10X", 0);
	test(__LINE__, "%-10.0X", 0);
	test(__LINE__, "%-10.1X", 0);
	test(__LINE__, "%-10.2X", 0);
	test(__LINE__, "%-10.10X", 0);
	test(__LINE__, "%-1.0X", -1);
	test(__LINE__, "%-1.1X", -1);
	test(__LINE__, "%-1.2X", -1);
	test(__LINE__, "%-1.10X", -1);
	test(__LINE__, "%-2.0X", -1);
	test(__LINE__, "%-2.1X", -1);
	test(__LINE__, "%-2.2X", -1);
	test(__LINE__, "%-2.10X", -1);
	test(__LINE__, "%-3.0X", -1);
	test(__LINE__, "%-3.1X", -1);
	test(__LINE__, "%-3.2X", -1);
	test(__LINE__, "%-3.10X", -1);
	test(__LINE__, "%-9.0X", UINT_MAX);
	test(__LINE__, "%-9.1X", UINT_MAX);
	test(__LINE__, "%-9.2X", UINT_MAX);
	test(__LINE__, "%-9.10X", UINT_MAX);
	test(__LINE__, "%-10.0X", UINT_MAX);
	test(__LINE__, "%-10.1X", UINT_MAX);
	test(__LINE__, "%-10.2X", UINT_MAX);
	test(__LINE__, "%-10.10X", UINT_MAX);
	test(__LINE__, "%-11.0X", UINT_MAX);
	test(__LINE__, "%-11.1X", UINT_MAX);
	test(__LINE__, "%-11.2X", UINT_MAX);
	test(__LINE__, "%-11.10X", UINT_MAX);
	test(__LINE__, "%01.0i", 0);
	test(__LINE__, "%01.1i", 0);
	test(__LINE__, "%01.2i", 0);
	test(__LINE__, "%01.10i", 0);
	test(__LINE__, "%02.0i", 0);
	test(__LINE__, "%02.1i", 0);
	test(__LINE__, "%02.2i", 0);
	test(__LINE__, "%02.10i", 0);
	test(__LINE__, "%010.0i", 0);
	test(__LINE__, "%010.1i", 0);
	test(__LINE__, "%010.2i", 0);
	test(__LINE__, "%010.10i", 0);
	test(__LINE__, "%01.0i", -1);
	test(__LINE__, "%01.1i", -1);
	test(__LINE__, "%01.2i", -1);
	test(__LINE__, "%01.10i", -1);
	test(__LINE__, "%02.0i", -1);
	test(__LINE__, "%02.1i", -1);
	test(__LINE__, "%02.2i", -1);
	test(__LINE__, "%02.10i", -1);
	test(__LINE__, "%03.0i", -1);
	test(__LINE__, "%03.1i", -1);
	test(__LINE__, "%03.2i", -1);
	test(__LINE__, "%03.10i", -1);
	test(__LINE__, "%09.0i", INT_MAX);
	test(__LINE__, "%09.1i", INT_MAX);
	test(__LINE__, "%09.2i", INT_MAX);
	test(__LINE__, "%09.10i", INT_MAX);
	test(__LINE__, "%010.0i", INT_MAX);
	test(__LINE__, "%010.1i", INT_MAX);
	test(__LINE__, "%010.2i", INT_MAX);
	test(__LINE__, "%010.10i", INT_MAX);
	test(__LINE__, "%011.0i", INT_MAX);
	test(__LINE__, "%011.1i", INT_MAX);
	test(__LINE__, "%011.2i", INT_MAX);
	test(__LINE__, "%011.10i", INT_MAX);
	test(__LINE__, "%01.0d", 0);
	test(__LINE__, "%01.1d", 0);
	test(__LINE__, "%01.2d", 0);
	test(__LINE__, "%01.10d", 0);
	test(__LINE__, "%02.0d", 0);
	test(__LINE__, "%02.1d", 0);
	test(__LINE__, "%02.2d", 0);
	test(__LINE__, "%02.10d", 0);
	test(__LINE__, "%010.0d", 0);
	test(__LINE__, "%010.1d", 0);
	test(__LINE__, "%010.2d", 0);
	test(__LINE__, "%010.10d", 0);
	test(__LINE__, "%01.0d", -1);
	test(__LINE__, "%01.1d", -1);
	test(__LINE__, "%01.2d", -1);
	test(__LINE__, "%01.10d", -1);
	test(__LINE__, "%02.0d", -1);
	test(__LINE__, "%02.1d", -1);
	test(__LINE__, "%02.2d", -1);
	test(__LINE__, "%02.10d", -1);
	test(__LINE__, "%03.0d", -1);
	test(__LINE__, "%03.1d", -1);
	test(__LINE__, "%03.2d", -1);
	test(__LINE__, "%03.10d", -1);
	test(__LINE__, "%09.0d", INT_MAX);
	test(__LINE__, "%09.1d", INT_MAX);
	test(__LINE__, "%09.2d", INT_MAX);
	test(__LINE__, "%09.10d", INT_MAX);
	test(__LINE__, "%010.0d", INT_MAX);
	test(__LINE__, "%010.1d", INT_MAX);
	test(__LINE__, "%010.2d", INT_MAX);
	test(__LINE__, "%010.10d", INT_MAX);
	test(__LINE__, "%011.0d", INT_MAX);
	test(__LINE__, "%011.1d", INT_MAX);
	test(__LINE__, "%011.2d", INT_MAX);
	test(__LINE__, "%011.10d", INT_MAX);
	test(__LINE__, "%01.0u", 0);
	test(__LINE__, "%01.1u", 0);
	test(__LINE__, "%01.2u", 0);
	test(__LINE__, "%01.10u", 0);
	test(__LINE__, "%02.0u", 0);
	test(__LINE__, "%02.1u", 0);
	test(__LINE__, "%02.2u", 0);
	test(__LINE__, "%02.10u", 0);
	test(__LINE__, "%010.0u", 0);
	test(__LINE__, "%010.1u", 0);
	test(__LINE__, "%010.2u", 0);
	test(__LINE__, "%010.10u", 0);
	test(__LINE__, "%01.0u", -1);
	test(__LINE__, "%01.1u", -1);
	test(__LINE__, "%01.2u", -1);
	test(__LINE__, "%01.10u", -1);
	test(__LINE__, "%02.0u", -1);
	test(__LINE__, "%02.1u", -1);
	test(__LINE__, "%02.2u", -1);
	test(__LINE__, "%02.10u", -1);
	test(__LINE__, "%03.0u", -1);
	test(__LINE__, "%03.1u", -1);
	test(__LINE__, "%03.2u", -1);
	test(__LINE__, "%03.10u", -1);
	test(__LINE__, "%09.0u", UINT_MAX);
	test(__LINE__, "%09.1u", UINT_MAX);
	test(__LINE__, "%09.2u", UINT_MAX);
	test(__LINE__, "%09.10u", UINT_MAX);
	test(__LINE__, "%010.0u", UINT_MAX);
	test(__LINE__, "%010.1u", UINT_MAX);
	test(__LINE__, "%010.2u", UINT_MAX);
	test(__LINE__, "%010.10u", UINT_MAX);
	test(__LINE__, "%011.0u", UINT_MAX);
	test(__LINE__, "%011.1u", UINT_MAX);
	test(__LINE__, "%011.2u", UINT_MAX);
	test(__LINE__, "%011.10u", UINT_MAX);
	test(__LINE__, "%01.0x", 0);
	test(__LINE__, "%01.1x", 0);
	test(__LINE__, "%01.2x", 0);
	test(__LINE__, "%01.10x", 0);
	test(__LINE__, "%02.0x", 0);
	test(__LINE__, "%02.1x", 0);
	test(__LINE__, "%02.2x", 0);
	test(__LINE__, "%02.10x", 0);
	test(__LINE__, "%010.0x", 0);
	test(__LINE__, "%010.1x", 0);
	test(__LINE__, "%010.2x", 0);
	test(__LINE__, "%010.10x", 0);
	test(__LINE__, "%01.0x", -1);
	test(__LINE__, "%01.1x", -1);
	test(__LINE__, "%01.2x", -1);
	test(__LINE__, "%01.10x", -1);
	test(__LINE__, "%02.0x", -1);
	test(__LINE__, "%02.1x", -1);
	test(__LINE__, "%02.2x", -1);
	test(__LINE__, "%02.10x", -1);
	test(__LINE__, "%03.0x", -1);
	test(__LINE__, "%03.1x", -1);
	test(__LINE__, "%03.2x", -1);
	test(__LINE__, "%03.10x", -1);
	test(__LINE__, "%09.0x", UINT_MAX);
	test(__LINE__, "%09.1x", UINT_MAX);
	test(__LINE__, "%09.2x", UINT_MAX);
	test(__LINE__, "%09.10x", UINT_MAX);
	test(__LINE__, "%010.0x", UINT_MAX);
	test(__LINE__, "%010.1x", UINT_MAX);
	test(__LINE__, "%010.2x", UINT_MAX);
	test(__LINE__, "%010.10x", UINT_MAX);
	test(__LINE__, "%011.0x", UINT_MAX);
	test(__LINE__, "%011.1x", UINT_MAX);
	test(__LINE__, "%011.2x", UINT_MAX);
	test(__LINE__, "%011.10x", UINT_MAX);
	test(__LINE__, "%01.0X", 0);
	test(__LINE__, "%01.1X", 0);
	test(__LINE__, "%01.2X", 0);
	test(__LINE__, "%01.10X", 0);
	test(__LINE__, "%02.0X", 0);
	test(__LINE__, "%02.1X", 0);
	test(__LINE__, "%02.2X", 0);
	test(__LINE__, "%02.10X", 0);
	test(__LINE__, "%010.0X", 0);
	test(__LINE__, "%010.1X", 0);
	test(__LINE__, "%010.2X", 0);
	test(__LINE__, "%010.10X", 0);
	test(__LINE__, "%01.0X", -1);
	test(__LINE__, "%01.1X", -1);
	test(__LINE__, "%01.2X", -1);
	test(__LINE__, "%01.10X", -1);
	test(__LINE__, "%02.0X", -1);
	test(__LINE__, "%02.1X", -1);
	test(__LINE__, "%02.2X", -1);
	test(__LINE__, "%02.10X", -1);
	test(__LINE__, "%03.0X", -1);
	test(__LINE__, "%03.1X", -1);
	test(__LINE__, "%03.2X", -1);
	test(__LINE__, "%03.10X", -1);
	test(__LINE__, "%09.0X", UINT_MAX);
	test(__LINE__, "%09.1X", UINT_MAX);
	test(__LINE__, "%09.2X", UINT_MAX);
	test(__LINE__, "%09.10X", UINT_MAX);
	test(__LINE__, "%010.0X", UINT_MAX);
	test(__LINE__, "%010.1X", UINT_MAX);
	test(__LINE__, "%010.2X", UINT_MAX);
	test(__LINE__, "%010.10X", UINT_MAX);
	test(__LINE__, "%011.0X", UINT_MAX);
	test(__LINE__, "%011.1X", UINT_MAX);
	test(__LINE__, "%011.2X", UINT_MAX);
	test(__LINE__, "%011.10X", UINT_MAX);
	test(__LINE__, "%*d", 0, 42);
	test(__LINE__, "%*d", 0, 0);
	test(__LINE__, "%*d", 10, 42);
	test(__LINE__, "%*d", -10, 42);
	test(__LINE__, "%0*d", -10, 42);
	test(__LINE__, "%0*d", 10, 42);
	test(__LINE__, "%0*d", 10, -42);
	test(__LINE__, "%0*d", 0, 42);
	test(__LINE__, "%0*d", 10, 0);
	test(__LINE__, "%0*d", -10, 0);
	test(__LINE__, "%*d", 010, 42);
	test(__LINE__, "%*s", 10, "Hello");
	test(__LINE__, "%*s", -10, "Hello");
	test(__LINE__, "%-*d", 10, 42);
	test(__LINE__, "%-*d", -10, 42);
	test(__LINE__, "%-*d", -10, -42);
	test(__LINE__, "%.*d", 0, 42);
	test(__LINE__, "%.*d", 10, 42);
	test(__LINE__, "%.*d", -10, 42);
	test(__LINE__, "%.*d", 0, 0);
	test(__LINE__, "%.*d", 10, 0);
	test(__LINE__, "%.-10d", 0);
	test(__LINE__, "%.*d", -10, 0);
	test(__LINE__, "%.*d", -0, 0);
	test(__LINE__, "%.*d", -0, 42);
	test(__LINE__, "%.*d", -0, -42);
	test(__LINE__, "%.*s", -3, "Hello");
	test(__LINE__, "%10.*d", 10, 42);
	test(__LINE__, "%*.10d", 10, 42);
	test(__LINE__, "%*.*d", 0, 0, 0);
	test(__LINE__, "%*.*d", 0, 0, 42);
	test(__LINE__, "%*.*d", 0, 0, -42);
	test(__LINE__, "%*.*d", 0, 5, 0);
	test(__LINE__, "%*.*d", 0, -5, 0);
	test(__LINE__, "%*.*d", 5, 0, 0);
	test(__LINE__, "%*.*d", -5, 0, 0);
	test(__LINE__, "%*.*d", 5, 5, 0);
	test(__LINE__, "%*.*s", 0, 0, "Hello");
	test(__LINE__, "%*.*s", 0, 0, "Hello");
	test(__LINE__, "%*.*s", 0, 0, "Hello");
	test(__LINE__, "%*.*s", 0, 5, "Hello");
	test(__LINE__, "%*.*s", 0, -5, "24Hello24");
	test(__LINE__, "%*.*s", 5, 0, "23Hello23");
	test(__LINE__, "%*.*s", -5, 0, "Hello22");
	test(__LINE__, "%*.*s", 5, 5, "Hello");
	test(__LINE__, "%n", NULL);
	test(__LINE__, "123%n ", &t2);
	test(__LINE__, "size = %d", t2);
	test(__LINE__, "%n ", &t2);
	test(__LINE__, "size = %d", t2);
	test(__LINE__, "%s %n ", "Hello", &t2);
	test(__LINE__, "size = %d", t2);
	test(__LINE__, "%10s %n ", "Hello", &t2);
	test(__LINE__, "size = %d", t2);
	test(__LINE__, "%10.2s %n ", "Hello", &t2);
	test(__LINE__, "size = %d", t2);
	test(__LINE__, "%10.2s %n %s %n", "Hello", &t2, "Hello2", &t2bis);
	test(__LINE__, "%c", 0b01000001);
	test(__LINE__, "%hhi", CHAR_MAX);
	test(__LINE__, "%hhi", CHAR_MAX + 1);
	test(__LINE__, "%hhi", CHAR_MIN);
	test(__LINE__, "%hhi", CHAR_MIN - 1);
	test(__LINE__, "%hhu", UCHAR_MAX);
	test(__LINE__, "%hhu", UCHAR_MAX + 1);
	test(__LINE__, "%hhx", UCHAR_MAX);
	test(__LINE__, "%hhx", UCHAR_MAX + 1);
	test(__LINE__, "%hi", SHRT_MAX);
	test(__LINE__, "%hi", SHRT_MAX + 1);
	test(__LINE__, "%hi", SHRT_MIN);
	test(__LINE__, "%hi", SHRT_MIN - 1);
	test(__LINE__, "%hu", USHRT_MAX);
	test(__LINE__, "%hu", USHRT_MAX + 1);
	test(__LINE__, "%hx", USHRT_MAX);
	test(__LINE__, "%hx", USHRT_MAX + 1);
	test(__LINE__, "%li", LONG_MAX);
	test(__LINE__, "%li", LONG_MAX + 1);
	test(__LINE__, "%li", LONG_MIN);
	test(__LINE__, "%li", LONG_MIN - 1);
	test(__LINE__, "%lu", ULONG_MAX);
	test(__LINE__, "%lu", ULONG_MAX + 1);
	test(__LINE__, "%lx", ULONG_MAX);
	test(__LINE__, "%lx", ULONG_MAX + 1);
	test(__LINE__, "%lli", LLONG_MAX);
	test(__LINE__, "%lli", LLONG_MAX + 1);
	test(__LINE__, "%lli", LLONG_MIN);
	test(__LINE__, "%lli", LLONG_MIN - 1);
	test(__LINE__, "%llu", ULLONG_MAX);
	test(__LINE__, "%llu", ULLONG_MAX + 1);
	test(__LINE__, "%llx", ULLONG_MAX);
	test(__LINE__, "%llx", ULLONG_MAX + 1);
	test(__LINE__, "%s ", s);
	test(__LINE__, "%lc ", 128519);
	test(__LINE__, "%lc ", 0x80000);
	test(__LINE__, "%lc ", 176);
	test(__LINE__, "%lc ", 35211);
	test(__LINE__, "%lc ", 0x7E);
	test(__LINE__, "%lc ", 0x7F);
	test(__LINE__, "%lc ", 0x80);
	test(__LINE__, "%lc ", 0x7FF);
	test(__LINE__, "%lc ", 0x800);
	test(__LINE__, "%lc ", 0xFFFF);
	test(__LINE__, "%lc ", 0x80000);
	test(__LINE__, "%lc %lc ", 0x13143, 0x13144);
	test(__LINE__, "%lc ", 256 + 48);
	test(__LINE__, "%6lc ", 176);
	test(__LINE__, "%6lc ", 35211);
	test(__LINE__, "%6lc ", 128519);
	test(__LINE__, "%-6lc ", 176);
	test(__LINE__, "%-6lc ", 35211);
	test(__LINE__, "%-6lc ", 312859);
	test(__LINE__, "%-6lc ", 18518);
	test(__LINE__, "%-6lc ", -18518);
	test(__LINE__, "%-6lc ", -10);
	test(__LINE__, "%.0ls ", t);
	test(__LINE__, "%1.0ls ", t);
	test(__LINE__, "%1ls ", t);
	test(__LINE__, "%.2ls ", t);
	test(__LINE__, "%.3ls ", t);
	test(__LINE__, "%.4ls ", t);
	test(__LINE__, "%.5ls ", t);
	test(__LINE__, "%.6ls ", t);
	test(__LINE__, "%.7ls ", t);
	test(__LINE__, "%15.0ls ", t);
	test(__LINE__, "%15.1ls ", t);
	test(__LINE__, "%15.2ls ", t);
	test(__LINE__, "%15.3ls ", t);
	test(__LINE__, "%15.4ls ", t);
	test(__LINE__, "%15.5ls ", t);
	test(__LINE__, "%15.6ls ", t);
	test(__LINE__, "%15.7ls ", t);
	test(__LINE__, "%16.7ls ", t);
	test(__LINE__, "%-15.0ls ", t);
	test(__LINE__, "%-15.1ls ", t);
	test(__LINE__, "%-15.2ls ", t);
	test(__LINE__, "%-15.3ls ", t);
	test(__LINE__, "%-15.4ls ", t);
	test(__LINE__, "%-15.5ls ", t);
	test(__LINE__, "%-15.6ls ", t);
	test(__LINE__, "%-15.7ls ", t);
	test(__LINE__, "%ls ", t);
	test(__LINE__, "%#x", 42);
	test(__LINE__, "%#10x", 42);
	test(__LINE__, "%#-10x", 42);
	test(__LINE__, "%#010x", 42);
	test(__LINE__, "%#10.4x", 42);
	test(__LINE__, "%#-10x", 0);
	test(__LINE__, "%#10.0x", 0);
	test(__LINE__, "%#X", 42);
	test(__LINE__, "%#10X", 42);
	test(__LINE__, "%#-10X", 42);
	test(__LINE__, "%#010X", 42);
	test(__LINE__, "%#10.4X", 42);
	test(__LINE__, "%#10X", 0);
	test(__LINE__, "%#10.0X", 0);
	test(__LINE__, "% i", 42);
	test(__LINE__, "% i", -42);
	test(__LINE__, "%0 10i", 42);
	test(__LINE__, "%0 10i", -42);
	test(__LINE__, "% 5i", 42);
	test(__LINE__, "% 3i", 42);
	test(__LINE__, "% .1i", 0);
	test(__LINE__, "% .0i", 0);
	test(__LINE__, "%)i", 10000);
	test(__LINE__, "%'i", 10000);
	test(__LINE__, "%'i", 0);
	test(__LINE__, "%'i", 999);
	test(__LINE__, "%'i", 1000);
	test(__LINE__, "%'i", 789456);
	test(__LINE__, "%'i", 1000000);
	test(__LINE__, "%'i", 999000000);
	test(__LINE__, "%'i", -10000);
	test(__LINE__, "%'i", -999);
	test(__LINE__, "%'i", -1000);
	test(__LINE__, "%'i", -789456);
	test(__LINE__, "%'u", 10000);
	test(__LINE__, "%'u", 0);
	test(__LINE__, "%'u", 999);
	test(__LINE__, "%'u", 1000);
	test(__LINE__, "%'u", 789456);
	test(__LINE__, "%'u", 1000000);
	test(__LINE__, "%'u", 999000000);
	test(__LINE__, "%'u", -10000);
	test(__LINE__, "%'u", -999);
	test(__LINE__, "%'u", -1000);
	test(__LINE__, "%'u", -789456);
	test(__LINE__, "%o", 042);
	test(__LINE__, "%o", 0);
	test(__LINE__, "%o", 8);
	test(__LINE__, "%10o", 042);
	test(__LINE__, "%.2o", 456789);
	test(__LINE__, "%-10.3o", 456789);
	test(__LINE__, "%#-10o", 042);
	test(__LINE__, "%#010o", 042);
	test(__LINE__, "%'o", 123456789);
	test(__LINE__, "%#.3x", 0);
	test(__LINE__, "%#.0x", 0);
	test(__LINE__, "%#.10x", 0);
	test(__LINE__, "%o", 0);
	test(__LINE__, "%.o", 0);
	test(__LINE__, "%.o", 1);
	test(__LINE__, "%#.o", 1);
	test(__LINE__, "%#.o", 0);
	test(__LINE__, "%#.0o", 0);
	test(__LINE__, "%#.-10o", 0);
	test(__LINE__, "%#.10o", 0);
	test(__LINE__, "%#.10o", 2);
	test(__LINE__, "%#.0o", 0);
	test(__LINE__, "%#.1x", 12);
	test(__LINE__, "%.1o", 2);
	test(__LINE__, "%#.2o", 2);
	test(__LINE__, "%#.1o", 2);
	test(__LINE__, "%.1o", 2);
	test(__LINE__, "%#.x", 1);
	test(__LINE__, "%#.0x", 1);
	test(__LINE__, "%#.10x", 1);
	test(__LINE__, "%#.o", 1);
	test(__LINE__, "%#.0o", 1);
	test(__LINE__, "%#.10o", 1);
	test(__LINE__, "%#.x", 10);
	test(__LINE__, "%#.0x", 10);
	test(__LINE__, "%#.10x", 10);
	test(__LINE__, "%#.o", 10);
	test(__LINE__, "%#100.2o", 100000);
	test(__LINE__, "%#.0o", 10);
	test(__LINE__, "%#.10o", 10);
	test(__LINE__, "%#x", 0);
	test(__LINE__, "%+x", 125);
	test(__LINE__, "% x", 125);
	test(__LINE__, "%#0+10.x", 0);
	test(__LINE__, "%#o", 0);
	test(__LINE__, "%+o", 125);
	test(__LINE__, "% o", 125);
	test(__LINE__, "%#0+10.o", 0);
	test(__LINE__, "st1 %*.*d\n", 10, 10, 50);
	test(__LINE__, "st2 %*.*d\n", 1, 50, 50);
	test(__LINE__, "st3 %*.*d\n", 0, 0, 50);
	test(__LINE__, "st4 %*.*d\n", 0, 50, 50);
	test(__LINE__, "st5 %*.*d\n", 10, 0, 50);
	test(__LINE__, "st6 %*.*d\n", 10, 10, 50);
	test(__LINE__, "st12 %*d\n", 10, 50);
	test(__LINE__, "st13 %*d\n", 0, 0);
	test(__LINE__, "st14 %.*d\n", 0, 0);
	test(__LINE__, "st15 %*d\n", 50, 5);
	test(__LINE__, "st16 %0.*d\n", 50, 5);
	test(__LINE__, "st17 %0.*d\n", 0, 0);
	test(__LINE__, "st7 %*.*s\n", 1, 50, "hey");
	test(__LINE__, "st8 %*.*s\n", 0, 0, "coucou");
	test(__LINE__, "st9 %*.*s\n", 0, 50, "hey");
	test(__LINE__, "st10 %*.*s\n", 10, 0, "dsa");
	test(__LINE__, "st11 %*.*s\n", 10, 10, "hello");
	test(__LINE__, "st8 %.*s\n", 0, "coucou");
	test(__LINE__, "st9 %*s\n", 0, "hey");
	test(__LINE__, "st10 %*s\n", 10, "dsa");
	test(__LINE__, "st118 %*s\n", 100, "hello");
	test(__LINE__, "st119 %*s\n", 1000, "hello");
	test(__LINE__, "st120 %*s\n", 10000, "hello");
	test(__LINE__, "st121 %*s\n", 100000, "hello");
	test(__LINE__, "st118 %*d\n", 100, 0);
	test(__LINE__, "st119 %*d\n", 1000, 10);
	test(__LINE__, "st120 %*d\n", 10000, 467);
	test(__LINE__, "st121 %*d\n", 100000, -589);
	test(__LINE__, "ultimate1 %*d        %*i\n", 500, 0, 10, 10);
	test(__LINE__, "ultimate2 %*d %*s %*x %*X %*i %*u\n", 1, 5000, 1, "hey", 10, 54700, 1, 300, 10000, -55, 1, -60);
	test(__LINE__, "ultimate3 %*.*d %*.*s\n", 1, 50, 5000, 1, 0, "hey");
	test(__LINE__, "ultimate4 %*.*x %*.*X\n", 1, 50, 5000, 1, 0, 10);
	test(__LINE__, "ultimate5 %*.*u\n", 1, 50, 5000);
	test(__LINE__, "neg1 %*s\n", -9, "coucou");
	test(__LINE__, "neg2 %*.*s\n", -9, 4, "coucou");
	test(__LINE__, "neg3 %*s\n", -9, NULL);
	test(__LINE__, "neg4 %*.*s\n", 0, 0, "coucou");
	test(__LINE__, "neg5 %*s\n", -100, "coucou");
	test(__LINE__, "neg6 %*s\n", -156, "coucou");
	test(__LINE__, "neg7 %*.*s\n", -1586, 15, "coucou");
	test(__LINE__, "neg8 %*.*s\n", -1586, 15, "coucou");
	test(__LINE__, "neg9 %*.*s\n", 15856, 155, "coucou");
	test(__LINE__, "neg10 %*.*s\n", -15586, 15, "coucou");
	test(__LINE__, "neg11 %*.*s\n", -15586, 15, "coucou");
	test(__LINE__, "neg1 %*d\n", -9, 150);             
	test(__LINE__, "neg2 %*.*d\n", -9, 4, 1555);       
	test(__LINE__, "neg3 %*d\n", -9, -255);
	test(__LINE__, "neg4 %*.*d\n", 0, 0, -30);         
	test(__LINE__, "neg5 %*d\n", -100, -589);          
	test(__LINE__, "neg6 %*d\n", -156, 15555);         
	test(__LINE__, "neg7 %*.*d\n", -1586, 15, 0);      
	test(__LINE__, "neg8 %*.*d\n", -1586, 15, 300);    
	test(__LINE__, "neg9 %*.*d\n", 15856, 155, -3000);                   
	test(__LINE__, "neg10   4 %*.*d\n", 4090, 15, 150);                    
	test(__LINE__, "neg11   3 %*.*d\n", 4090, 15, 0);                      
	test(__LINE__, "***************%*s%*d**************%*4u*************\n", 10, "coucou", 10, 10, -50, 20);
	test(__LINE__, "******%*s%*d**************%*.*u*****\n", 10, "coucou", 10, 10, -50, -5 ,20);
	test(__LINE__, "taaa %100s\n", "hello");
	test(0, 0);
	return (0);
}
